name: Test and Report

on:
  push:
    branches:
      - main  # ajuste conforme necessário
  pull_request:
    branches:
      - main  # ajuste conforme necessário

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Create log/report directory
      run: mkdir -p log/report

    - name: Run tests and generate reports
      run: |
        cucumber -t @Regressao --format json --format html --out=log/report.html
        
    - name: Download report
      uses: actions/upload-artifact@v2
      with:
        name: test_reports
        path: |
          log/report/report.html
