name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9,11,15,18 * * 1,2,3,4,5"

# permite também executar esse workflow manualmente na aba "Actions" do GitHub
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Cucumber
        run: bundle exec cucumber

      - name: Install additional gems
        run: |
          gem install faker site_prism report_builder

      - name: Run Cucumber with Faker and SitePrism
        run: bundle exec cucumber

      - name: Install Dependencies
        run: gem install report_builder  # Install ReportBuilder gem if not already installed 

      - name: Run Hooks
        run: ruby test/features/support/hooks.rb

      - name: Upload test report
        if: always() # Always run this step, even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: cucumber_report.json
