name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Cucumber
        run: bundle exec cucumber

      - name: Run Capybara with Selenium
        run: bundle exec cucumber -p selenium

      - name: Install additional gems
        run: |
          gem install faker site_prism report_builder

      - name: Run Cucumber with Faker and SitePrism
        run: bundle exec cucumber -p site_prism

      - name: Generate test report
        if: always() # Always run this step, even if previous steps fail
        run: bundle exec report_builder --json-folder=tmp/cucumber && mv tmp/cucumber/report.json cucumber_report.json

      - name: Upload test report
        if: always() # Always run this step, even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: cucumber_report.json
