name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9,12,15,18 * * 1,2,3,4,5"

# permite também executar esse workflow manualmente na aba "Actions" do GitHub
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create results directory
        run: mkdir -p results

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Cucumber
        run: bundle exec cucumber
     
      - name: Run Cucumber with Faker and SitePrism
        run: bundle exec cucumber

      - name: Generate HTML report with ReportBuilder
        run: |
          REPORT_TITLE="Relatório de Testes"
          REPORT_PATH="results/report.html"
          REPORT_BUILDER_PATH="results"
          report-builder --json-path=results/report.json --report-path=$REPORT_BUILDER_PATH --report-title="$REPORT_TITLE" --color --report-logs
