name: Test and Report

on:
  push:
    branches:
      - main  # ajuste conforme necessário
  pull_request:
    branches:
      - main  # ajuste conforme necessário

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        # Comando para executar os testes automatizados, por exemplo:
        bundle exec rspec

    - name: Generate YAML report
      run: |
        # Execute o script que gera o relatório YAML usando report_builder
        ruby features/support/hooks.rb
