name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9,12,15,18 * * 1,2,3,4,5"

# permite também executar esse workflow manualmente na aba "Actions" do GitHub
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create results directory
        run: mkdir -p results

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Cucumber
        run: bundle exec cucumber

      - name: Install additional gems
        run: |
          gem install faker site_prism report_builder

      - name: Run Cucumber with Faker and SitePrism
        run: bundle exec cucumber

      - name: Passo - Armazenar relatório HTML
        uses: actions/upload-artifact@v3
        # Expressão condicional para que sempre seja executado independentemente dos resultados dos steps anteriores
        if: ${{ always() }}
        with: 
          name: reports
          path: ./log/report.json
          # Armazena o relatório HTML por 30 dias
          retention-days: 30
          
      - name: Generate HTML report
        run: bundle exec cucumber --format html --out=results/report.html
