name: Run Tests and Generate Report

on: [push]

jobs:
  test-and-generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7' # ou a versão que você está usando
      
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Tests and Generate Report
      run: |
        cucumber --format json -o log/report.json
      continue-on-error: true

    - name: Generate Report
      if: always()
      run: |
        t=$(date +"%d-%m-%Y")
        report-builder --input-path log/report.json --report-path log/report_$t --report-types html --report-title "Bradoc - Testes Automatizados" --additional-info "Dispositivo: WEB, Data do Teste: $t" --color blue
